### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by Were-Logan-0110** [import-pandas-as-numpy/pyobfuscate-decoder#1]
```sql
Traceback (most recent call last):
  File "E:\fbvenv\Auto_Share\pyobfuscate-decoder\pyobfuscate_decoder\decoder.py", line 75, in <module>       
    main()
  File "E:\fbvenv\Auto_Share\pyobfuscate-decoder\pyobfuscate_decoder\decoder.py", line 59, in main
    extracted_payload = extract_payload(args.filename)
  File "E:\fbvenv\Auto_Share\pyobfuscate-decoder\pyobfuscate_decoder\decoder.py", line 12, in extract_payload
    return re.search(bytes_regex, payload)[0]
TypeError: 'NoneType' object is not subscriptable
```
the obfuscated file
[share-pro.txt](https://github.com/import-pandas-as-numpy/pyobfuscate-decoder/files/14727535/share-pro.txt)

**Comment by import-pandas-as-numpy** [comment]
This error is raised due to the regex statement not detecting double quoted byte strings. I will fix this temporarily, but I have an ast aware fix that can be used to circumvent this issue entirely.

**Comment by Were-Logan-0110** [comment]
> This error is raised due to the regex statement not detecting double quoted byte strings. I will fix this temporarily, but I have an ast aware fix that can be used to circumvent this issue entirely.

okk

**Comment by Were-Logan-0110** [comment]
> This error is raised due to the regex statement not detecting double quoted byte strings. I will fix this temporarily, but I have an ast aware fix that can be used to circumvent this issue entirely.

i just tried replacing the " and still didnot work it wrote another obfuscated byte string

**Comment by import-pandas-as-numpy** [comment]
> > This error is raised due to the regex statement not detecting double quoted byte strings. I will fix this temporarily, but I have an ast aware fix that can be used to circumvent this issue entirely.
> 
> i just tried replacing the " and still didnot work it wrote another obfuscated byte string

It is not base case aware, you will need to step through each round of encoding until you reach the final marshalled payload, which will then be emitted in the console. In the future I'd like the opportunity to write this to a `.pyc` file.

**Comment by Were-Logan-0110** [comment]
> > > This error is raised due to the regex statement not detecting double quoted byte strings. I will fix this temporarily, but I have an ast aware fix that can be used to circumvent this issue entirely.
> > 
> > 
> > i just tried replacing the " and still didnot work it wrote another obfuscated byte string
> 
> It is not base case aware, you will need to step through each round of encoding until you reach the final marshalled payload, which will then be emitted in the console. In the future I'd like the opportunity to write this to a `.pyc` file.

![image](https://github.com/import-pandas-as-numpy/pyobfuscate-decoder/assets/123822233/33fbdaf3-e855-4ac1-93c1-e704170a177d)

**Comment by import-pandas-as-numpy** [comment]
I'll have to test this a bit more. I'll take care of this in the coming days.
